/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.imgTabla;
import Modelo.Usuario;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo Caiza
 */
public class VentanaGestionarContacto extends javax.swing.JFrame {

    Usuario usuarioActual;
    String direccionActual;
        
    public VentanaGestionarContacto() {
        initComponents();
    }
     public VentanaGestionarContacto(Usuario usu,String direccion) {
        initComponents();
        this.setLocationRelativeTo(null);
        usuarioActual=usu;
        propiedadesTabla();
        direccionActual=direccion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAmigo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableAmigo = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jTableAmigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Imagen ", "Nombre", "Correo", "Enviar"
            }
        ));
        jTableAmigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableAmigo.getTableHeader().setResizingAllowed(false);
        jTableAmigo.getTableHeader().setReorderingAllowed(false);
        jTableAmigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAmigoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAmigo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 540, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAmigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAmigoMouseClicked
        //aceder a la posicion en x en la tabla q se va a coreesponder con el objeto de la listaamigo
        int x=jTableAmigo.rowAtPoint(evt.getPoint());
        System.out.println("x: "+x);
        VentanaModificarContacto mc=new VentanaModificarContacto(usuarioActual,direccionActual,x);
        mc.setVisible(true);
    }//GEN-LAST:event_jTableAmigoMouseClicked

        private void propiedadesTabla() {
        jTableAmigo.setDefaultRenderer(Object.class, new imgTabla());
        String titulos[] = {"Imagen", "Nombre", "Correo"};
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        Object[]columna=new Object[modelo.getColumnCount()];
        for (int i=0;i<usuarioActual.getListaAmigo().size();i++) {
         
           columna[0]=(new JLabel(usuarioActual.getListaAmigo().get(i).getImagen()));
            columna[1]=usuarioActual.getListaAmigo().get(i).getNombre();
            columna[2]=usuarioActual.getListaAmigo().get(i).getCorreo();
           
            modelo.addRow(columna);
        }
        jTableAmigo.setRowHeight(60);
       
        jTableAmigo.setModel(modelo);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestionarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestionarContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAmigo;
    // End of variables declaration//GEN-END:variables
}
