/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import Panel.PanelEnviar;
import Control.Archivo;
import Control.CambiaPanel;
import Modelo.Usuario;
import Vista.Menu;

public class PanelMensajeRecibido extends javax.swing.JPanel {

    private Usuario usuarioActual;
    private String direccionActual;
    private int posicion;
    private Archivo file=new Archivo();

    public PanelMensajeRecibido(Usuario usu, int pos,String dir) {
        initComponents();
        usuarioActual = usu;
        posicion = pos;
        direccionActual=dir;
        jLabelAsunto.setText(usuarioActual.getListaRecibidos().get(pos).getAsunto());
        jLabelEmisor.setText(usuarioActual.getListaRecibidos().get(pos).getEmisor());
        jTextAreaReceptor.setText(usuarioActual.getListaRecibidos().get(pos).getDestinatario());
        jTextAreaContenido.setText(usuarioActual.getListaRecibidos().get(pos).getContenido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAsunto = new javax.swing.JLabel();
        jLabelEmisor1 = new javax.swing.JLabel();
        jLabelEmisor = new javax.swing.JLabel();
        jLabelPara = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaReceptor = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaContenido = new javax.swing.JTextArea();
        jButtonRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAsunto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelAsunto.setText("Asunto");
        add(jLabelAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabelEmisor1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelEmisor1.setText("Emisor:");
        add(jLabelEmisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelEmisor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelEmisor.setText("Emisor");
        add(jLabelEmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabelPara.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPara.setText("Para:");
        add(jLabelPara, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTextAreaReceptor.setEditable(false);
        jTextAreaReceptor.setColumns(20);
        jTextAreaReceptor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextAreaReceptor.setLineWrap(true);
        jTextAreaReceptor.setRows(5);
        jScrollPane2.setViewportView(jTextAreaReceptor);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 500, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reenviar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 153, -1, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basurero.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        jTextAreaContenido.setEditable(false);
        jTextAreaContenido.setColumns(20);
        jTextAreaContenido.setLineWrap(true);
        jTextAreaContenido.setRows(5);
        jScrollPane1.setViewportView(jTextAreaContenido);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 590, 320));

        jButtonRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        jButtonRegresar.setBorder(null);
        jButtonRegresar.setContentAreaFilled(false);
        jButtonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //remover de la lista recibido
        usuarioActual.getListaRecibidos().remove(posicion);
        //rescribir el archivo
        Usuario usuarioModifificado = new Usuario(usuarioActual.getNombre(), usuarioActual.getCorreo(), usuarioActual.getClave(), usuarioActual.getImagen(),
                usuarioActual.getListaAmigo(), usuarioActual.getListaEnviados(), usuarioActual.getListaRecibidos(), usuarioActual.getListaGrupos(),
        usuarioActual.getListaBorrador());
        file.modificar(usuarioModifificado, direccionActual);
        //mostramos panel de recibidos
       new  CambiaPanel(Menu.pnlPrincipal, new PanelRecibido(usuarioActual));
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CambiaPanel(Menu.pnlPrincipal, new PanelEnviar(usuarioActual, usuarioActual.getListaRecibidos().get(posicion)));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed

        new CambiaPanel(Menu.pnlPrincipal, new PanelRecibido(usuarioActual));
    }//GEN-LAST:event_jButtonRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabelAsunto;
    private javax.swing.JLabel jLabelEmisor;
    private javax.swing.JLabel jLabelEmisor1;
    private javax.swing.JLabel jLabelPara;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaContenido;
    private javax.swing.JTextArea jTextAreaReceptor;
    // End of variables declaration//GEN-END:variables
}
